name: Monitor Docript
on:
  schedule:
    - cron: '*/5 * * * *' # S'exécute toutes les 5 minutes
  workflow_dispatch:      # Permet de le lancer manuellement pour tester

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Check Site Status
        run: |
          STATUS=$(curl -o /dev/null -s -w "%{http_code}" https://docript.fr)
          if [ "$STATUS" -ne 200 ]; then
            echo "Le site est down avec le code $STATUS"
            curl -d "ALERTE : Ton site docript.fr est DOWN (Code $STATUS). Switch sur Netlify !" ntfy.sh/site_docript_bapwep_098465874995322647821154477885
          else
            echo "Le site est en ligne (Code 200)"
          fi